### PR TITLE
[Fix] miss transration

### PR DESCRIPTION
**Pull request by yoshi1125hisa**

### CODE REVIEW

**Comment by chenshuai2144** [comment]
Comment using your own language, I think there is no problem

**Comment by yoshi1125hisa** [comment]
@chenshuai2144 
Yes. I felt OK.
But this is something that is being discussed among many Japanese developers.
In particular, it is said that it is difficult to grasp these meanings in Japanese.

**Comment by chenshuai2144** [comment]
You are right, I don't know Japan

**Comment by yoshi1125hisa** [comment]
@chenshuai2144 
Thanks:)

**Pull request merged**
