### PR TITLE
feat: add Japanese translation

### PR DESCRIPTION
**Pull request by kevinadhiguna**
Hello, I added Japanese `ja-JP` translation. However I am looking forward to add translation on pages as it is still a basic setup. Any suggestions will be appreciated, thanks.

### CODE REVIEW

**Comment by kevinadhiguna** [comment]
> ## -description': 'To Doタスクは、内部レターの形式で通知されます',
> 
> https://github.com/ant-design/ant-design-pro/blob/211b8ee48f442bb1d526cfcd8449eedf55be2e59/src/locales/ja-JP/settings.ts#L56-L59
> 
> ###### This comment was generated by [todo](https://todo.jasonet.co) based on a `todo` comment in [211b8ee](https://github.com/ant-design/ant-design-pro/commit/211b8ee48f442bb1d526cfcd8449eedf55be2e59) in #7722. cc @kevinadhiguna.

Pardon me, what does this comment mean? I think initially it was because some lines of Japanese translations remained empty. Nevertheless, I have just already filled in the rest of Japanese translation but it still displays.

**Comment by chenshuai2144** [comment]
todo action

**Comment by kevinadhiguna** [comment]
> todo action tools

All right, thanks. I think I have added all I can in this PR.

**Comment by ceefour** [comment]
@kevinadhiguna the todo bot is mistakenly adding these lines as todo's, although they are legitimately part of the source files. I think you can safely ignore them.

Someone should try to fix the todo bot settings in this repo, as it's now confusing and spamming the issue comments with false notes.

**Comment by kevinadhiguna** [comment]
> @kevinadhiguna the todo bot is mistakenly adding these lines as todo's, although they are legitimately part of the source files. I think you can safely ignore them.
> 
> Someone should try to fix the todo bot settings in this repo, as it's now confusing and spamming the issue comments with false notes.

I really appreciate this, thanks for your help.

**Comment by kevinadhiguna** [comment]
@chenshuai2144 pardon me, any updates on this PR? Is there anything I can do/fix?

**Pull request merged**
