### PR TITLE
feat: add count prop for NoticeIconTab component

### PR DESCRIPTION
**Pull request by anyuxuan**
Add new prop count for NoticeIconTab Component.
prop count?: number is not required.
eg. If you wanna show unread message count, you could use this prop.

### CODE REVIEW

**Comment by chenshuai2144** [comment]
merge master

**Comment by anyuxuan** [comment]
Have merged

**Comment by chenshuai2144** [comment]
Can you help me with a demo?

**Comment by anyuxuan** [comment]
我们用中文交流吧.【捂脸】
代码已经提交，包含DEMO

1. 将原来显示所有通知数量改成了显示未读通知数量
2. 点击每一条未读通知，会将状态改变成已读状态，同时UI会相应改变，总的未读数量也会改变

**Pull request merged**
