### PR TITLE
Enhance stylelint rules, fix propTypes error of TagSelect

### PR DESCRIPTION
**Pull request by laozhu**
## Commits in this PR:

- [x] Support CSS modules rules with [stylelint-config-css-modules](https://github.com/pascalduez/stylelint-config-css-modules)
- [x] Support no-ignored-properties rule with [stylelint-declaration-block-no-ignored-properties](https://github.com/kristerkari/stylelint-declaration-block-no-ignored-properties)
- [x] Support sorted CSS properties order with [stylelint-order](https://github.com/hudochenkov/stylelint-order) and [stylelint-config-rational-order](https://github.com/constverum/stylelint-config-rational-order)
- [x] Autofix order of all less files by lint:fix script
- [x] Fix CSS pseudo element with double colon
- [x] Fix propTypes error of [TagSelect](https://github.com/ant-design/ant-design-pro/blob/master/src/components/TagSelect/index.js#L21) component
- [ ] Write document for code style and IDEs integrated

## Using vscode

If you are using vscode with [vscode-stylelint](https://github.com/shinnn/vscode-stylelint) extension, this is my vscode config for stylelint (with [vscode-prettier](https://github.com/prettier/prettier-vscode) extension installed).

```jsonc
{
  "editor.formatOnSave": true,

  // Stylelint
  // https://github.com/shinnn/vscode-stylelint#optional-but-recommended-setup
  "css.validate": false,
  "less.validate": false,
  "scss.validate": false,

  // Prettier
  "prettier.stylelintIntegration": true,
}
``` 

With these configs, when you save your CSS, SCSS or LESS files, vscode will automatically sort your CSS properties and fix some fixable stylelint rules.

## Using others

If you are using other IDEs or editors, the config should be different from vscode, but you can fix all files just run script below in your terminal:

```bash
# using npm
$ npm run lint:fix

# using yarn
$ yarn lint:fix
```

### CODE REVIEW

**Comment by chenshuai2144** [comment]
Great, but css sorting makes me feel bad.

**Comment by laozhu** [comment]
@chenshuai2144 Maybe too strict for writing CSS? I use this with vscode and vscode-stylelint extension, set editor.formatOnSave to true, It will be automatically sorted while I’m saving file.

If you don’t like css sorting, I will revert the commits of css sorting today.

**Comment by laozhu** [comment]
@chenshuai2144 I have removed CSS sorting from this PR.

**Comment by chenshuai2144** [comment]
If it can be sorted automatically, I think it is good, no need to delete

**Comment by laozhu** [comment]
@chenshuai2144 I have got CSS sorting feature back 😄

**Comment by chenshuai2144** [comment]
ok，This will be a great job

**Comment by chenshuai2144** [comment]
why？
```
  "css.validate": false,
  "less.validate": false,
  "scss.validate": false,
```

**Comment by laozhu** [comment]
@chenshuai2144 vscode will make another duplicate lint info, see below link:

<https://github.com/shinnn/vscode-stylelint#optional-but-recommended-setup>

**Comment by chenshuai2144** [comment]
Can add a document for use in each ide

**Comment by laozhu** [comment]
@chenshuai2144 I am not familiar with other IDEs or editors, but I think `npm run lint:fix` is what they want 😄. I am very happy to contribute document about stylelint and others, but where should I commit to?

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-site

**Comment by laozhu** [comment]
@chenshuai2144 Can I add a code style section of ant-design-pro there? I will write sth about prettier, eslint, tslint and stylelint in this section.

**Comment by chenshuai2144** [comment]
@laozhu  有兴趣帮 antd 也搞一下吗？

**Comment by chenshuai2144** [comment]
> * Write document for code style and IDEs integrated 
Create a new issue  in the site

**Comment by laozhu** [comment]
@chenshuai2144 没问题的，晚上搞起来。

**Pull request merged**
