### PR TITLE
Improve getFlatMenuKeys & getMeunMatchKeys for better readability and robustness

### PR DESCRIPTION
**Pull request by AlanWei**
## getFlatMenuKeys
The purpose of `getFlatMenuKeys` is to form a flat array from a nested array so that using `Array.reduce` might be a better approach to concat formatted value to the final result one by one instead of `Array.forEach`.

Using `Array.reduce` also can ensure the formatted flat array remain the same elements order as the original nested array.

For example, if we have the menu data like below:
```javascript
const menu = [{
  path: '/dashboard',
  children: [{
    path: '/dashboard/name',
  }],
}, {
  path: '/userinfo',
  children: [{
    path: '/userinfo/:id',
    children: [{
      path: '/userinfo/:id/info',
    }],
  }],
}];
```

Before `getFlatMenuKeys` will return
```javascript
[ '/dashboard/name',
  '/dashboard',
  '/userinfo/:id/info',
  '/userinfo/:id',
  '/userinfo' ]
```

By using `Array.reduce` we could get
```javascript
[ '/dashboard',
  '/dashboard/name',
  '/userinfo',
  '/userinfo/:id',
  '/userinfo/:id/info' ]
```

In addition, since `getFlatMenuKeys` has no dependencies on specific Component so that I changed it to a normal function which could be exported easily.

## getMeunMatchKeys
Before `getMeunMatchKeys` is used to filter each possible path with the return of `urlToList`. In order to avoid using `Array.map` every time when we want to call `getMeunMatchKeys`, I passed in the return of `urlToList` as a param so that developer can call `getMeunMatchKeys` like this:

```javascript
getMeunMatchKeys(this.flatMenuKeys, urlToList(pathname));
```
Since we are passing each of possible path to `getMeunMatchKeys`, the filter result from `pathToRegexp` will not be duplicate. We could safely concat them and form the final result. In this way, we could also avoid using `[0]` or `.pop()` to improve code robustness. And by using `Array.reduce`, we don't need to filter `undefined` value for those error path cases whereas `Array.map` will have this problem.

---

I added some tests in `SilderMenu.test.js` as well to make sure this function refactor won't break anything. 🙂

### CODE REVIEW

**Comment by chenshuai2144** [comment]
You did a good job

**Comment by ccn1010** [comment]
const menu = [{
  path: '/dashboard',
  children: [{
    path: '/dashboard/name',
  }],
}, {
  path: '/userinfo',
  children: [{
    path: '/userinfo/:id',
    children: [{
      path: '/userinfo/:id/info',
    }],
  }],
}];
请问menu的path写成这样如何实现点击跳转？点击还是/userinfo/:id/info，而不是/userinfo/1/info这样

**Comment by ccn1010** [comment]
```
const menu = [{
path: '/dashboard',
children: [{
path: '/dashboard/name',
}],
}, {
path: '/userinfo',
children: [{
path: '/userinfo/:id',
children: [{
path: '/userinfo/:id/info',
}],
}],
}];
```
请问menu的path写成这样如何实现点击跳转？点击还是/userinfo/:id/info，而不是/userinfo/1/info这样

**Comment by ccn1010** [comment]
```
const menu = [{
  path: '/dashboard',
  children: [{
    path: '/dashboard/name',
  }],
}, {
  path: '/userinfo',
  children: [{
    path: '/userinfo/:id',
    children: [{
      path: '/userinfo/:id/info',
    }],
  }],
}];
```
请问menu的path写成这样如何实现点击跳转？点击还是/userinfo/:id/info，而不是/userinfo/1/info这样

**Pull request merged**
