### PR TITLE
🔥 clean: remove unuse code

### PR DESCRIPTION
**Pull request by chenshuai2144**
close https://github.com/ant-design/ant-design/issues/24725
close https://github.com/ant-design/ant-design-pro/issues/6759
close https://github.com/ant-design/ant-design-pro-layout/issues/490
close https://github.com/ant-design/ant-design-pro-layout/issues/489
close https://github.com/ant-design/ant-design-pro/issues/6761

### CODE REVIEW

**Comment by chenshuai2144** [comment]
ref  https://github.com/umijs/route-utils/releases/tag/v1.0.14

**Comment by afc163** [comment]
ci 全挂了。

**Comment by chenshuai2144** [comment]
eslint 的问题有点坑。

**Comment by chenshuai2144** [comment]
https://eslint.org/docs/user-guide/migrating-to-7.0.0#plugin-resolution-has-been-updated
理论上应该不会有问题

**Pull request merged**
