### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by ja573**
Two sets of config files that enable dockerisation of ant design pro:

### Usage
Build: `docker-compose -f ./docker/docker-compose.yml build`
Deploy: `docker-compose -f ./docker/docker-compose.yml up`
### Files:
- ./docker/Dockerfile
- ./docker/docker-compose.yml
- ./docker/nginx.conf

### Usage
Build: `docker-compose -f ./docker/docker-compose.dev.yml build`
Run: `docker-compose -f ./docker/docker-compose.dev.yml up`

### Files
- ./docker/Dockerfile.dev
- ./docker/docker-compose.dev.yml

### CODE REVIEW

**Comment by chenshuai2144** [comment]
Add a secondary directory, so there are too many files

**Comment by ja573** [comment]
@chenshuai2144 I've moved all docker-related files to `./docker/` - I've also updated my comment above to reflect the changes

**Comment by chenshuai2144** [comment]
good job

**Comment by chenshuai2144** [comment]
I can't use it。
```
Service 'ant-design-pro_build' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder028577509/package.json: no such file or directory
```
我应该做什么操作

**Pull request merged**
