### PR TITLE
Fix #3232 - fix stopping the development server after tests

### LINKED ISSUE #3232: `npm run test:all` doesn't stop the development server after tests
Steps to reproduce:

1. Run `npm run test:all`, all tests pass.
2. Run `npm run test:all` again.

Expected behavior: the second run should run all tests and the tests should pass.

Actual behavior: the output is `Something is already running on port 8000.`, the script exits without running any tests.

Ant Design Pro version: a5d1979
Platform: Ubuntu 18.10

### PR DESCRIPTION
**Pull request by EvgenyOrekhov**
Fixes #3232.

### CODE REVIEW

**Comment by EvgenyOrekhov** [comment]
Not sure why `ci/circleci: test` fails. Everything passes on my machine.

**Comment by EvgenyOrekhov** [comment]
Can anybody help me with CircleCI? I don't know how to deal with `Error: spawn lsof ENOENT`.

**Comment by chenshuai2144** [comment]
you can try meger master

**Comment by chenshuai2144** [comment]
this is a bad function

**Pull request closed without merging**
