### PR TITLE
fix(List): width of search input overflow in mobile mode

### PR DESCRIPTION
**Pull request by anyuxuan**
#4162

### CODE REVIEW

**Comment by chenshuai2144** [comment]
New [here](https://github.com/ant-design/pro-blocks,)。
If you can, here is the whole pr

**Comment by anyuxuan** [comment]
> New [here](https://github.com/ant-design/pro-blocks,)。
> If you can, here is the whole pr
链接404

**Comment by chenshuai2144** [comment]
sorry 

https://github.com/ant-design/pro-blocks

**Comment by anyuxuan** [comment]
谢谢，我看一下去

**Pull request merged**
