### PR TITLE
Translate charts

### PR DESCRIPTION
**Pull request by lorecrafting**
CN to EN translation of Chart components

### CODE REVIEW

**Comment by nikogu** [comment]
非常感谢，不过 charts 的底层正在升级 https://github.com/ant-design/ant-design-pro/pull/370 ，暂时还不能合并，等底层升级好了，可能需要 rebase 一下然后合并进来

**Comment by lorecrafting** [comment]
Awesome, thank you, i'll wait for the upgrade before rebasing and fixing.  In the meantime i'll work on other components.

**Comment by chenshuai2144** [comment]
Chart has been upgraded. You can start the job

**Comment by ddcat1115** [comment]
@RaoHai  is working on this, and I will close this pr

**Pull request closed without merging**
