### PR TITLE
Use redux connected router

### PR DESCRIPTION
**Pull request by andriijas**
timetravel etc

### CODE REVIEW

**Comment by chenshuai2144** [comment]
The benefit of doing this is？

**Comment by andriijas** [comment]
dva is already using react-router redux and ant-design-pro is already dispatching actions on it in multiple places

example:

https://github.com/ant-design/ant-design-pro/blob/master/src/models/form.js#L28https://github.com/ant-design/ant-design-pro/blob/master/src/routes/List/List.js#L14

by using connected router you actually put route changes in the redux store.

**Comment by chenshuai2144** [comment]
@ddcat1115  合了吧。特好用

**Comment by afc163** [comment]
Still don't see the different from regular Router.

**Comment by chenshuai2144** [comment]
@afc163  这个可以将路由信息保存在stroe state里面。
 `const { pathname } = Store.getState().routing.location;`
如果不用这个 pathname === null

**Pull request merged**
