### PR TITLE
🌎 localization: docs translated to english

### PR DESCRIPTION
**Pull request by mattortiz**

### CODE REVIEW

**Comment by brlala** [comment]
I'm opposed to this, we should leave the docstrings in the language that the library maintainer is most comfortable with, which is Chinese.

**Comment by chenshuai2144** [comment]
Or you can keep both languages, the maintainer of this repository speaks Chinese and most users speak Chinese

**Comment by mattortiz** [comment]
I'll work on an edit that supports both languages, if I may. Our team is eager to leverage and support this toolchain.

**Comment by chenshuai2144** [comment]
Maybe we can keep both kinds of comments, like this
```
/**
 * @zh-cn 单选 Switch
 * @en-us Single Choice Switch
 */
```

**Comment by CodeDoctorDE** [comment]
i want to use this library too. I cannot speak and read chinese, because of this, it would be cool if it would be translated in english. Additionally english is a lingua franca

**Comment by chenshuai2144** [comment]
@CodeDoctorDE  The Chinese Internet has its own ecology and has no less a number of engineers than the entire world.
Our company is also a Chinese company and we pay more attention to the Chinese user experience

**Comment by CodeDoctorDE** [comment]
Because of this, It would be cool to have multi language like on the main page of ant design

**Comment by kevinadhiguna** [comment]
> Because of this, It would be cool to have multi language like on the main page of ant design

I think it is possible to use `useIntl` and `FormattedMessage` components from umiJS, isn't it? If it is so, you do not have to hard code the translation. In other words, Ant Design will be able to display in multi languages (actually, it already is).

**Comment by ncioj10** [comment]
@chenshuai2144 I think there are a lot of foreign users of this library and as large parts of the github information etc. are already available in English, I don't see why there shouldn't be an English option on the website. I understand that you are a chinese company and that there are a large number of chinese developers using this library, but I'm sure that the library would benefit very much if English is persistently an option. 
As a sidenote I would also recommend to at least enforce English bug titles, as I think it creates a lot of duplication if foreigners create another ticket for issues already filed. This would also make it possible for more people to help out on errors. 
I think you can profit of the very experiences European and American open source developers that are currently being kept away due to poor translation and ressources and would make the overal library more popular.

**Comment by chenshuai2144** [comment]
I agree with some of your points, but I think it's better to have them all.
The number of English issues is not particularly large, and I don't see any problem with repetition.

Many Chinese are submitting English through translation software, and English is not very friendly to junior developers

**Pull request merged**
