### PR TITLE
fix #4079 PageHeaderWrapper margin in xs screen

### LINKED ISSUE #4079: xs屏幕下PageHeaderWrapper的外边距疑问
在v1和稍早之前的v2版本中在screen-xs下，PageHeaderWrapper外边距是显示的
BaiduShurufa_2019-4-25_15-16-20

最近发现这个边距没有消失
BaiduShurufa_2019-4-25_15-16-37

这个情况是故意为之的嘛？看着有点浪费空间。。:joy:

### PR DESCRIPTION
**Pull request by zhang0ZGC**
https://github.com/ant-design/ant-design-pro/blob/b86048b4db8d5c17241e08b29a2226f6318529a5/src/components/PageHeaderWrapper/index.less#L1-L11

rename .content to .children-content

### CODE REVIEW

**Comment by chenshuai2144** [comment]
image
要不要顺便修一下这个

**Comment by zhang0ZGC** [comment]
OK，我瞅瞅

**Comment by zhang0ZGC** [comment]
.main .extraContent优先级大于.extraContent，将media query代码移入.main

**Comment by chenshuai2144** [comment]
优秀的同学

**Pull request merged**
