### PR TITLE
NoticeIcon: using Dropdown instead of Popover.

### PR DESCRIPTION
**Pull request by rayronvictor**

### CODE REVIEW

**Comment by rayronvictor** [comment]
Before and after
captura de tela 2018-12-04 as 09 16 13

**Comment by chenshuai2144** [comment]
Why do you want to do this?

**Comment by xiaohuoni** [comment]
Why delete the arrow?

**Comment by rayronvictor** [comment]
My purpose with this PR was:
- to create a behavioral consistence between the RightContent menu items.
- on mobile, the popover arrow was buggy.

**Comment by afc163** [comment]
It will miss the arrow in popover card which is signicant for design.

**Comment by rayronvictor** [comment]
Also, I will try to create a new component that basically extends Dropdown but will be full width on mobile.

This new component can be used in NoticeIcon, Account menu, SelectLang, etc.

**Comment by rayronvictor** [comment]
captura de tela 2018-12-04 as 11 06 53

**Comment by chenshuai2144** [comment]
Your efforts make Pro more powerful.

**Pull request merged**
