### PR TITLE
Use prevState inside setState instead of this.state

### LINKED ISSUE #1122: Do not use this.state within this.setState(...)
Because of the asynchronous nature of setState(...) and because of batch updating in react, you can't predict the content of this.state. It might work most of the time, but its unsafe by nature.

It's way better to use prevState to update state if you really need to update it based on the previous state.

I found countless occasions in ant-design-pro where you do that. You can read more about why this is dangerous [here](https://medium.freecodecamp.org/functional-setstate-is-the-future-of-react-374f30401b6b).

### PR DESCRIPTION
**Pull request by chillyistkult**
Fixes #1122

### CODE REVIEW

**Comment by afc163** [comment]
I don't think we should use prevState in every setState.

**Comment by chillyistkult** [comment]
Then you still have the problem that you cannot predict the content of this.state at the time of execution of setState. If React decides to do a batch update this.state might not be what you expect it to be. So I don't think this is a good practice after all.

**Comment by chenshuai2144** [comment]
This is a good, AsyncMode may need him.

**Comment by chenshuai2144** [comment]
先关掉了。。。。这个pr 的意义也许没那么大

**Pull request closed without merging**
