### PR TITLE
fix: judgment condition of autoHideHeader switch

### PR DESCRIPTION
**Pull request by F-loat**
autoHideHeader 的选项应该在 fixedHeader 开启时显示

### CODE REVIEW

**Comment by F-loat** [comment]
https://github.com/umijs/umi/blob/master/packages/babel-preset-umi/package.json#L19
依赖确实刚好低了一个版本，但是我本地打包出来的文件是没问题的，试了下单独指定  `plugin-proposal-decorators` 为最新版本也还是不行，这个问题大概是从 #1533 这个 pr 开始出现，可能和 https://github.com/ant-design/ant-design-pro/commit/3cfbae3b31e5fdf665f312be4c11b5dcca25987c 有关系?

**Comment by TomasRas** [comment]
Having same issue here.
My package json :
`"devDependencies": {
    "@babel/core": "7.0.0-beta.44",
    "@babel/plugin-proposal-decorators": "^7.0.0-beta.49",
    "@babel/plugin-syntax-jsx": "^7.0.0-beta.49",
    "@babel/plugin-transform-react-jsx": "^7.0.0-beta.44",
    "@babel/preset-env": "^7.0.0-beta.49",
    "@babel/register": "^7.0.0-beta.49",
    "autoprefixer": "^8.4.1",
    "babel-eslint": "^8.2.3",
    "babel-loader": "^8.0.0-beta.0",
    "compression-webpack-plugin": "^1.1.11",
    "copy-webpack-plugin": "^4.5.1",
    "css-loader": "^0.28.11",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-plugin-import": "^2.12.0",
    "file-loader": "^1.1.11",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "html-webpack-plugin": "^3.2.0",
    "jasmine": "^3.1.0",
    "jasmine-snapshot": "^1.8.1",
    "jsdom": "^11.11.0",
    "mini-css-extract-plugin": "^0.4.0",
    "node-sass": "^4.9.0",
    "postcss-loader": "^2.1.5",
    "resolve-url-loader": "^2.3.0",
    "rimraf": "^2.6.2",
    "sass-loader": "^7.0.3",
    "sinon": "^5.1.1",
    "style-loader": "^0.21.0",
    "uglifyjs-webpack-plugin": "^1.2.5",
    "webpack": "^4.12.0",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-cli": "^3.0.2",
    "webpack-dev-server": "^3.1.4"
  }     


`

**Comment by sorrycc** [comment]
是需要升级 babel 版本到 49 吗？

**Comment by F-loat** [comment]
也不一定是 babel 版本的问题，因为本地打包出来是没问题的，可以再试下，其实之前我还尝试过回退到早之前的版本 4bec5248b930c16abfc5afb17f85535a44046158 ，这个当时应该是没问题的，但是好像现在也不行，因为提交间隔的时间不很长，不确定是不是有缓存的影响

**Comment by F-loat** [comment]
这个 pr 没问题的话可以先合并了？

**Pull request merged**
