### PR TITLE
Authorized component now depends on store instead of local storage

### PR DESCRIPTION
**Pull request by kamote**
- add login model as part of initial reducer
 - fetch data from localStorage as initial state
 - wrap AuthorizedRoute to pass down currentAuthority
 - use subscribe instead of direct access to localStorage
 -  drill down currentAuthority props to any Components needs it
 - set default authority to `guest`
- remove file `src/utils/Authorized.js`

### CODE REVIEW

**Comment by chenshuai2144** [comment]
What formatting tools did you use?

**Comment by kamote** [comment]
Hi @chenshuai2144 i'm using eslint as a formatter i've disabled prettier since it is not compatible w/ the current format. I've manually indented some lines for example https://github.com/kamote/ant-design-pro/blob/23d1ca7189ac9253e1ca96af08beffd4cafb6a6a/src/layouts/BasicLayout.js#L147

should i return in to one-line format?

**Comment by chenshuai2144** [comment]
solve the conflict

**Comment by kamote** [comment]
@chenshuai2144 Please review again, rebase it against master

**Comment by chenshuai2144** [comment]
Ok

**Comment by chenshuai2144** [comment]
I tried it. Your idea is not a good idea.
Thank you for your code.
But this pr can cause serious problems

**Pull request merged**
